// ZEHRA KINIK - Ilk giris ipuclari (App::hint kimlikleri) ve Ingilizce karsiliklari (Lang.cpp tam cumle tablosu).
#pragma once

namespace zk {

enum HintId { HintGarage = 0, HintDrag, HintRoad, HintParts, HintLeague, HintEcu, HintChase, HintMap, HintSetup, HintStreet, HintGauges, HintCount };

inline const char* const* hintTexts() {
    static const char* const t[HintCount] = {
        "GARAJA HOSGELDIN!\nYARIS: HARITA, LIGLER, TURNUVA\nPARCA: MODIFIYE   KURULUM: SUSPANSIYON / LASTIK\n"
        "KADRAN: GOSTERGE AL   BOYA: RENK, SERIT, JANT\nSOKAK: GECE BULUSMASI, DYNO YARISMASI, MUSTERI\nGAZ: BASILI TUT, MOTORU DINLE",
        "DRAG KALKISI\n1) DEBRIYAJA BAS, KOLU 1. VITESE GOTUR\n2) GAZLA DEVRI KALKIS DEVRINDE TUT\n"
        "3) YESILDE DEBRIYAJI BIRAK (COK HIZLI = PATINAJ)\n4) KIRMIZI CIZGIDE: DEBRIYAJ + SONRAKI VITES\nSONUCTA GRAFIK: PATINAJ VE VITES NOKTALARI",
        "YOL SURUSU\nDIREKSIYON: SOL / SAG (TELEFONU EGEREK DE)\nKAYAN ARAC KENDI TOPARLANMAZ: KARSI DIREKSIYON + GAZ\n"
        "GECE VE YAGMURDA TUTUS DUSER, ERKEN FRENLE\nSU 108 C USTU: GUC KAYBI (SOGUTMAYI YUKSELT)",
        "MODIFIYE\nILK DOKUNUS: ONIZLEME (GUC, YUK, 1/4 MIL)\nIKINCI DOKUNUS: SATIN AL VE TAK\nMOTOR / SANZIMAN YUKU %100'U GECMESIN\n"
        "BUYUK TURBO: POMPA + ENJEKTOR, ARA SOGUTUCU\nVE YUKSEK OKTAN ISTER (YOKSA VURUNTU)",
        "KARIYER\nHER LIGDE 3 GALIBIYET -> PATRON YARISI\nPATRONU YEN -> SONRAKI LIG ACILIR\nPINK SLIP: KAYBEDEN ARABASINI VERIR!\n"
        "GUNLUK GOREVLER VE BASARIMLAR: EK ODUL",
        "ECU YAZILIM\nHER ECU'NUN YAZILIM YUVASI VE SEVIYE SINIRI VAR\nHARITA: STAGE 1-3   DEVIR: +250 ADIM\n"
        "KESICI SUPAP SINIRINI ASARSA SUPAP ATAR\nSTANDALONE: VURUNTU KONTROL MODULU AL",
        "POLIS KACIS\nPOLIS ARKADAN GELIYOR: 400 M ACIL VE 4 S TUT\nYA DA 5 KM'YI BITIR\n"
        "DIBINDEYKEN YAVASLAMA, CARPMA: YAKALANIRSIN\nKENARDA KIRMIZI / MAVI ISIK = POLIS YAKIN",
        "BOLGE HARITASI\nBOLGEYE DOKUN: O BOLGENIN ETKINLIKLERI\nKILITLI BOLGE: ONCEKI LIGIN PATRONUNU YEN\n"
        "HAFTALIK TURNUVA: 3 TUR ELEME, BUYUK ODUL",
        "KURULUM\nLASTIK BASINCI: DUSUK = KALKIS TUTUSU\nAYARLI SUSPANSIYONLA: YUKSEKLIK, YAY, VIRAJ DEMIRI\n"
        "PROFIL: DRAG / YOL / PIST AYARINI KAYDET VE YUKLE\nNOS TUPU BURADA DOLAR",
        "SOKAK\nBULUSMA: BAHISLI DRAG, POLIS BASKINI OLABILIR\nDYNO: HAFTADA BIR, EN GUCLU KAZANIR\n"
        "MUSTERI: ARACI HEDEF BEYGIRE CIKAR, GARAJDA TESLIM ET",
        "KADRAN\nSATIRA DOKUN: USTTE CANLI ONIZLEME\nALDIGIN KADRANA DONMEK UCRETSIZ\nTURBO GOSTERGESI YALNIZ ASIRI BESLEMELI MOTORDA",
    };
    return t;
}
inline const char* const* hintTextsEn() {
    static const char* const t[HintCount] = {
        "WELCOME TO THE GARAGE!\nRACE: MAP, LEAGUES, TOURNAMENT\nPARTS: TUNING   SETUP: SUSPENSION / TIRES\n"
        "GAUGES: BUY A CLUSTER   PAINT: COLOR, STRIPE, RIMS\nSTREET: NIGHT MEETUP, DYNO CONTEST, CUSTOMERS\nGAS: HOLD IT, LISTEN TO THE ENGINE",
        "DRAG LAUNCH\n1) PRESS THE CLUTCH, MOVE THE LEVER TO 1ST\n2) HOLD THE REVS AT LAUNCH RPM\n"
        "3) RELEASE THE CLUTCH ON GREEN (TOO FAST = WHEELSPIN)\n4) AT THE REDLINE: CLUTCH + NEXT GEAR\nRESULTS GRAPH: WHEELSPIN AND SHIFT POINTS",
        "ROAD DRIVING\nSTEER: LEFT / RIGHT (OR TILT THE PHONE)\nA SLIDING CAR WONT RECOVER BY ITSELF: COUNTERSTEER + THROTTLE\n"
        "GRIP DROPS AT NIGHT AND IN THE RAIN, BRAKE EARLY\nWATER OVER 108 C: POWER LOSS (UPGRADE COOLING)",
        "TUNING\nFIRST TAP: PREVIEW (POWER, LOAD, 1/4 MILE)\nSECOND TAP: BUY AND FIT\nKEEP ENGINE / GEARBOX LOAD UNDER 100%\n"
        "BIG TURBO: PUMP + INJECTORS, INTERCOOLER\nAND HIGH OCTANE (OR IT KNOCKS)",
        "CAREER\n3 WINS IN EACH LEAGUE -> BOSS RACE\nBEAT THE BOSS -> NEXT LEAGUE UNLOCKS\nPINK SLIP: THE LOSER GIVES UP THEIR CAR!\n"
        "DAILY TASKS AND ACHIEVEMENTS: EXTRA REWARDS",
        "ECU SOFTWARE\nEVERY ECU HAS SOFTWARE SLOTS AND LEVEL LIMITS\nMAP: STAGE 1-3   REV LIMIT: +250 STEPS\n"
        "IF THE LIMITER EXCEEDS THE VALVE LIMIT, VALVES FLOAT\nSTANDALONE: BUY THE KNOCK CONTROL MODULE",
        "POLICE ESCAPE\nTHE POLICE ARE BEHIND YOU: OPEN 400 M AND HOLD 4 S\nOR FINISH 5 KM\n"
        "DONT SLOW DOWN OR CRASH WHEN THEY ARE CLOSE: BUSTED\nRED / BLUE GLOW AT THE EDGES = POLICE NEAR",
        "REGION MAP\nTAP A REGION: ITS EVENTS\nLOCKED REGION: BEAT THE PREVIOUS LEAGUE BOSS\nWEEKLY TOURNAMENT: 3 KNOCKOUT ROUNDS, BIG PRIZE",
        "SETUP\nTIRE PRESSURE: LOW = LAUNCH GRIP\nWITH ADJUSTABLE SUSPENSION: HEIGHT, SPRINGS, ANTI-ROLL BARS\n"
        "PROFILES: SAVE AND LOAD DRAG / ROAD / TRACK SETUPS\nREFILL THE NOS BOTTLE HERE",
        "STREET\nMEETUP: DRAG FOR A BET, POLICE MAY RAID\nDYNO: ONCE A WEEK, MOST POWER WINS\n"
        "CUSTOMER: REACH THE TARGET HP, DELIVER IN THE GARAGE",
        "GAUGES\nTAP A ROW: LIVE PREVIEW ON TOP\nSWITCHING BACK TO AN OWNED CLUSTER IS FREE\nBOOST GAUGE ONLY ON FORCED INDUCTION",
    };
    return t;
}

} // namespace zk
